### ISSUE TITLE
Sharing cart ad-hoc tasks on CELF does not run

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#159]
**Describe the bug**
Copy a section from this course: https://moodle.celf.dk/course/view.php?id=2779
It does not seem to copy them to the sharing cart..

**To Reproduce**
1. Go to https://moodle.celf.dk/course/view.php?id=2779
2. Copy a section. Check if its copied to the sharing cart
4. If it just stalls and does not copy anything, check : https://moodle.celf.dk/admin/tool/task/adhoctasks.php
5. There is errors in the failed backup tasks. And these jobs do not dissappear: 
![image](https://github.com/user-attachments/assets/63a5eb14-a3ea-46fb-b85e-2f16a2e5eca8)

**Ticket link**
https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3761855451?interaction=email

**Related issues**

**Comment by frederikmillingpytlick** [comment]
Awaiting #156 where I've introduced a more advanced logging.

**Comment by frederikmillingpytlick** [comment]
Log:
```
Execute adhoc task: block_sharing_cart\task\asynchronous_backup_task
Adhoc task id: 275202
Adhoc task custom data: {"backupid":"11c7a26ff5d2ea49fb93a09c3af00474","item":{"id":8688,"user_id":2,"file_id":null,"parent_item_id":null,"old_instance_id":21890,"type":"section","name":"Mundtlig pr\u00f8ve 2024","status":0,"sortorder":null,"timecreated":1723098757,"timemodified":1723098757},"backup_settings":{"users":false,"anonymize":false}}
... started 08:32:42. Current memory use 10.7 MB.
Processing asynchronous backup for backup: 11c7a26ff5d2ea49fb93a09c3af00474
Executing before_backup_started_hook...
Excluding activities which are disabled on the site...
...Including activity: (id: 457801)
...Including activity: (id: 453600)
...Including activity: (id: 453601)
Executing before_backup_started_hook completed, continuing with backup...
Kan ikke finde dataposten i databasetabellen course.
#0 /var/www/html/moodle/lib/dml/moodle_database.php(1630): moodle_database->get_record_select('course', 'WHERE id = ?', Array, 'id,category', 2)
#1 /var/www/html/moodle/lib/classes/context/course.php(200): moodle_database->get_record('course', Array, 'id,category', 2)
#2 /var/www/html/moodle/backup/util/helper/async_helper.class.php(147): core\context\course::instance('21890')
#3 /var/www/html/moodle/backup/util/helper/async_helper.class.php(129): async_helper->get_resource_link()
#4 [internal function]: async_helper->lookup_message_variables(Array)
#5 /var/www/html/moodle/backup/util/helper/async_helper.class.php(174): preg_replace_callback('/\\{([-_A-Za-z0-...', Array, 'Moodle {operati...')
#6 /var/www/html/moodle/blocks/sharing_cart/classes/task/asynchronous_backup_task.php(68): async_helper->send_message()
#7 /var/www/html/moodle/lib/classes/cron.php(508): block_sharing_cart\task\asynchronous_backup_task->execute()
#8 /var/www/html/moodle/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task(Object(block_sharing_cart\task\asynchronous_backup_task))
#9 /var/www/html/moodle/lib/classes/cron.php(128): core\cron::run_adhoc_tasks(1723098762, 0, true, 1723098761)
#10 /var/www/html/moodle/admin/cli/cron.php(186): core\cron::run_main_process('0')
#11 {main}
... used 240 dbqueries
... used 0.57027316093445 seconds
Adhoc task failed: block_sharing_cart\task\asynchronous_backup_task,Kan ikke finde dataposten i databasetabellen course.
```

**Comment by frederikmillingpytlick** [comment]
It's the setting `backup_async_message_users` that causes this error in Moodle core.

I've submitted a tracker issue for Moodle to look at:
[MDL-82750](https://tracker.moodle.org/browse/MDL-82750)

@superfoght you can close the issue when you're done testing it :)
